# Generated by Django 2.2 on 2019-04-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=50)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('plot', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=1000)),
                ('metascore', models.CharField(max_length=100)),
                ('imdbrating', models.CharField(max_length=100)),
                ('imdbvotes', models.CharField(max_length=100)),
                ('imdbid', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('dvd', models.CharField(max_length=100)),
                ('boxoffice', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
