# Generated by Django 2.2 on 2019-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=102),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbrating',
            field=models.CharField(max_length=107),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbvotes',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=104),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(max_length=106),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='website',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=103),
        ),
    ]
